# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='사전',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('단어', models.CharField(max_length=20)),
                ('품사', models.CharField(max_length=10)),
                ('빈도', models.IntegerField(default=1)),
            ],
        ),
    ]
