# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='사전',
            name='빈도',
        ),
        migrations.AddField(
            model_name='사전',
            name='국적',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='사전',
            name='출처',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='사전',
            name='품사2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
