# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnm', '0002_auto_20171106_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='사전',
            name='Tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
