# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnm', '0003_사전_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='알고리즘',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=20)),
                ('설명', models.TextField()),
                ('Voted', models.IntegerField(default=100)),
            ],
        ),
    ]
