# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnm', '0004_알고리즘'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='알고리즘',
            new_name='Algorithm',
        ),
    ]
