# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnm', '0005_auto_20171108_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='Voted',
            new_name='Votes',
        ),
    ]
