# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnm', '0006_auto_20171108_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='내용',
            field=models.TextField(blank=True, null=True),
        ),
    ]
