# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnm', '0007_algorithm_내용'),
    ]

    operations = [
        migrations.AlterField(
            model_name='사전',
            name='품사',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
