# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='임시사전',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('단어', models.CharField(max_length=20)),
                ('품사', models.CharField(blank=True, max_length=10, null=True)),
                ('품사2', models.CharField(blank=True, max_length=10, null=True)),
                ('국적', models.CharField(blank=True, max_length=10, null=True)),
                ('Tag', models.CharField(blank=True, max_length=10, null=True)),
                ('출처', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
